Added game XO
Alex-javac/FreeIt_Roman pull request #5
Opened 2021-03-03 22:18 UTC by Alex-javac

Без классов и методов получилось очень много строк)))

2021-03-27 23:03 UTC, michaelkotor commented on src/gameXO/GameXO.java
> +                char xo = count % 2 == 0 ? 'X' : 'O';//каждый ход миняем знак либо Х либо О
я бы повыносил это в константы

2021-03-28 09:42 UTC, Alex-javac commented on src/gameXO/GameXO.java
> +                char xo = count % 2 == 0 ? 'X' : 'O';//каждый ход миняем знак либо Х либо О
а на что это повлияет?

2021-03-28 10:03 UTC, EvgeniyTsarkov commented on src/gameXO/GameXO.java
> +                char xo = count % 2 == 0 ? 'X' : 'O';//каждый ход миняем знак либо Х либо О
Исключит человеческий фактор.

2021-03-28 13:50 UTC, Alex-javac commented on src/gameXO/GameXO.java
> +                char xo = count % 2 == 0 ? 'X' : 'O';//каждый ход миняем знак либо Х либо О
константа — величина, значение которой не меняется;
а это значение меняется каждый ход

2021-03-28 13:54 UTC, Alex-javac commented on src/gameXO/GameXO.java
> +                char xo = count % 2 == 0 ? 'X' : 'O';//каждый ход миняем знак либо Х либо О
если честно я не понимаю...
я поменяю это на константы и придется написать доп логику вместо одной строки

2021-03-28 14:28 UTC, Alex-javac commented on src/gameXO/GameXO.java
> +                char xo = count % 2 == 0 ? 'X' : 'O';//каждый ход миняем знак либо Х либо О
Исправил ))) 
уже все объяснили)

2021-03-28 14:30 UTC, michaelkotor requested changes

2021-03-28 14:30 UTC, michaelkotor commented on src/gameXO/GameXO.java
> +                        if (aChar != '\u0000') {//проверяем сколько осталось пустых элементов
а что это значит char?

2021-03-28 14:30 UTC, michaelkotor commented on src/gameXO/GameXO.java
> +        System.out.println("Игра окончена");
очень надеюсь ты это тестировал)

2021-03-28 14:30 UTC, michaelkotor commented on src/gameXO/GameXO.java
> +                        if (aChar != '\u0000') {//проверяем сколько осталось пустых элементов
я про \u0000

2021-03-28 14:56 UTC, Alex-javac commented on src/gameXO/GameXO.java
> +                        if (aChar != '\u0000') {//проверяем сколько осталось пустых элементов
Это значит не пустой char (null)

2021-03-28 14:59 UTC, Alex-javac commented on src/gameXO/GameXO.java
> +        System.out.println("Игра окончена");
Конечно))))
но всегда есть сомнения)

2021-03-28 15:00 UTC, Alex-javac commented on src/gameXO/GameXO.java
> +                        if (aChar != '\u0000') {//проверяем сколько осталось пустых элементов
по дефолту char \u0000

2021-04-12 08:27 UTC, michaelkotor commented on src/gameXO/GameXO.java
> +                        if (aChar != '\u0000') {//проверяем сколько осталось пустых элементов
я бы тогда исполььзовал Char как обертку и сравнивал с null, но можно и так

2021-04-12 08:28 UTC, michaelkotor approved these changes

2021-04-12 20:19 UTC, merged