Lesson4
Alex-javac/FreeIt_Roman pull request #7
Opened 2021-03-10 22:01 UTC by Alex-javac

задачи 26 и 27 решил разными способами

2021-03-11 08:59 UTC, VictorGuschenko commented on src/lesson4/Task25.java
> +            return false;
Снимаем 310 $  операция не может быть выполнена, вижу что купюр достаточно чтобы выдать 100+100+50+20+20+20 = 310 
Снимаем 360 - не достаточно купюр в банке

2021-03-11 19:45 UTC, Alex-javac commented on src/lesson4/Task25.java
> +            return false;
Спасибо что указал на ошибку.
недочеты в коде исправил)))

2021-03-27 22:56 UTC, michaelkotor requested changes

2021-03-27 22:56 UTC, michaelkotor commented on src/lesson4/Task24.java
> +            res = 0;
можно без этой переменной, возвращать сразу значение, будет на один блок меньше

2021-03-27 22:56 UTC, michaelkotor commented on src/lesson4/Task25.java
> +        if (cash % 10 != 0 || cash <= 0) {
как мне лучше выделять проверки в отдельные методы, это лучше читается

2021-03-27 22:56 UTC, michaelkotor commented on src/lesson4/Task25.java
> +
это точно надо поделить на функции)
для начала, определить, какими можно отдать, потом вычитать, это очень сложно

2021-03-27 22:56 UTC, michaelkotor commented on src/lesson4/Task28.java
> +public class Task28<T extends Number> {
разве этот класс сможет хранить int?)

2021-03-27 22:56 UTC, michaelkotor commented on src/lesson4/task27/Main.java
> +        if (cashMachine.withdraw(200)) {
а чем отличаются `withdraw ` от `debit`?

2021-03-27 22:56 UTC, michaelkotor commented on src/lesson4/task27/MasterCard.java
> +    private final char VALUTA ='€';
я бы это сделал enum

2021-03-27 22:56 UTC, michaelkotor commented on src/lesson4/task27/DebitCard.java
> +    String customerName;
модификатор доступа?

2021-03-27 22:56 UTC, michaelkotor commented on src/lesson4/task27/DebitCard.java
> +    GregorianCalendar expiryDate;
есть более новые классы для работы с датой, пакет `java.time.*`

2021-03-27 22:56 UTC, michaelkotor commented on src/lesson4/task26/Main.java
> +        MicrowaveOven micro = new MicrowaveOven("LG","power3000",300,
а можно здесь задание?

2021-03-28 10:00 UTC, Alex-javac commented on src/lesson4/Task24.java
> +            res = 0;
точно подмечено) спасибо

2021-03-28 13:16 UTC, Alex-javac commented on src/lesson4/task27/DebitCard.java
> +    GregorianCalendar expiryDate;
спасибо исправил

2021-03-28 13:19 UTC, Alex-javac commented on src/lesson4/task27/Main.java
> +        if (cashMachine.withdraw(200)) {
withdraw - списывает деньги с банкомата
 debit - списывает деньги с карты если банкомат может выдать деньги

2021-03-28 13:22 UTC, Alex-javac commented on src/lesson4/task27/MasterCard.java
> +    private final char VALUTA ='€';
исправил

2021-03-28 14:09 UTC, michaelkotor commented on src/lesson4/Task28.java
> +public class Task28<T extends Number> {
ладно, не может, просто условие так поставлено)

2021-03-28 14:11 UTC, michaelkotor commented on src/lesson4/task27/DebitCard.java
> +    String customerName;
я про private, стилистика

2021-03-28 14:11 UTC, michaelkotor approved these changes

2021-03-28 15:18 UTC, Alex-javac commented on src/lesson4/task27/DebitCard.java
> +    String customerName;
Уже исправил

2021-03-28 17:15 UTC, merged