Lesson6
Alex-javac/FreeIt_Roman pull request #9
Opened 2021-03-25 22:45 UTC by Alex-javac

@Аннотация

2021-03-27 22:59 UTC, michaelkotor requested changes

2021-03-27 22:59 UTC, michaelkotor commented on src/lesson6/Runner.java
> +                Object obj = clazz.newInstance();//создаем экземпляр класса
мы подразумеваем, что есть пустой конструктор?

2021-03-27 22:59 UTC, michaelkotor commented on src/lesson6/Runner.java
> +                methods(service, obj);
почему 2 раза?

2021-03-28 09:28 UTC, Alex-javac commented on src/lesson6/Runner.java
> +                Object obj = clazz.newInstance();//создаем экземпляр класса
по условию да)
//Класс MyService должен иметь переменные c private модификаторами,
// конструктор по умолчанию, get и set методы,
// переопределенные методы equals и hashcode,
// а так же private метод (private thisClassInfo),
// который будет просто печатать данные о самом классе (данные любые на ваш выбор),
// в котором он определен.

2021-03-28 09:30 UTC, Alex-javac commented on src/lesson6/Runner.java
> +                methods(service, obj);
для того чтобы проверить изменились ли поля

2021-03-28 14:06 UTC, michaelkotor approved these changes

2021-03-28 15:02 UTC, merged